Apache Ambari:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/ambari/
  code-host-name: svn.apache.org
  git-org-name: asf
  git-repo-name: ambari
  git-default-branch: main
  layout: standard
