allura:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/allura
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

ambari:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/ambari
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

ant:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/ant
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

apr:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/apr
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

beam:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/beam
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

board:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/board
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

bugs:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/bugs
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

cocoon:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/cocoon
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

comdev:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/comdev
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

commons:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/commons
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

crunch:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/crunch/site
  code-host-name: svn.apache.org
  git-org-name: asf
  layout: standard
  fetch-batch-size: 100

curator:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/curator/site
  code-host-name: svn.apache.org
  git-org-name: asf
  layout: standard
  fetch-batch-size: 100

datafu:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/datafu/site
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

db:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/db
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

eagle:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/eagle
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

falcon:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/falcon
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

fundraising:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/fundraising
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

httpcomponents:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/httpcomponents
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

httpd:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/httpd
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

infrastructure:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/infrastructure
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

jackrabbit:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/jackrabbit
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

johnzon:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/johnzon
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

karaf:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/karaf
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

knox:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/knox
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

kylin:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/kylin
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

lens:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/lens
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

lucene:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/lucene
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

manifoldcf:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/manifoldcf
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

maven:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/maven
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

openoffice:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/openoffice
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

parquet:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/parquet/site
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

pdfbox:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/pdfbox
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

perl:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/perl
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

phoenix:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/phoenix
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

poi:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/poi
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

reef:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/reef/site
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

spamassassin:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/spamassassin
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

subversion:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/subversion
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

tomcat:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/tomcat
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

twill:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/twill
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

uima:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/uima
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

usergrid:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/usergrid/site
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

xerces:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/xerces
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

xmlbeans:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/xmlbeans
  code-host-name: svn.apache.org
  git-org-name: asf
  fetch-batch-size: 100

zest:
  type: SVN
  svn-repo-code-root: https://svn.apache.org/repos/asf/zest/site
  code-host-name: svn.apache.org
  git-org-name: asf
