version: '2.4'

services:

  cloud-agent:
    container_name: cloud-agent
    image: index.docker.io/sourcegraph/src-tunnel-agent:2024-02-05-22-28-333320ee
    volumes:
      - ./config/service-account-key.json:/service-account-key.json
      - ./config/config.yaml:/config.yaml
    command: ["-config=/config.yaml"]
    restart: always
    networks:
      - sourcegraph

  src-serve-git:
    container_name: src-serve-git-wsl.local
    image:  index.docker.io/sourcegraph/src-cli:latest
    volumes:
      - ../repos-to-serve/:/repos-to-serve:ro
    command: "serve-git -addr :80 /repos-to-serve"
    networks:
      - sourcegraph

networks:
  sourcegraph:
