name: Docker Image CI

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - edited
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/sourcegraph/bridge-repo-converter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{raw}}
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=insiders,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=insiders-$(date +%Y-%m-%d--%H-%M-%S),enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=sha,prefix=
            type=sha,prefix=,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: bridge-repo-converter/build
          platforms: linux/amd64,linux/arm64
          file: bridge-repo-converter/build/Dockerfile
          push: true
          sbom: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
      - name: Inspect
        run: |
          docker image inspect ghcr.io/sourcegraph/bridge-repo-converter:$GITHUB_SHA
